import React, { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import Header from "../../components/GeneralUI/Header";
import Head from "next/head";
import { motion } from "framer-motion";
import BottomContents from "../../components/MenuPage/BottomContents";
import FilterOption from "../../components/MenuPage/FIlterOption";
import SwiperInstantiation from "../../components/MenuPage/SwiperInstantiation";
import { uiActions } from "../../store/ui-slice";
import ModalBackground from "../../components/MenuPage/ModalBackground";

const mon_com = [
  {
    img: "https://swiperjs.com/demos/images/nature-1.jpg",
    name: "Mỳ ý phô mai chay",
  },
  {
    img: "https://swiperjs.com/demos/images/nature-2.jpg",
    name: "Mỳ ý phô mai chay ngon",
  },
  {
    img: "https://swiperjs.com/demos/images/nature-3.jpg",
    name: "Cơm chay",
  },
  {
    img: "https://swiperjs.com/demos/images/nature-4.jpg",
    name: "Cơm chay ngon",
  },
];

const mon_soi = [
  {
    img: "https://swiperjs.com/demos/images/nature-1.jpg",
    name: "rau chay",
  },
  {
    img: "https://swiperjs.com/demos/images/nature-2.jpg",
    name: "nấm",
  },
  {
    img: "https://swiperjs.com/demos/images/nature-3.jpg",
    name: "Cơm chay",
  },
];

const filter_options = [
  "Món cơm",
  "Món sợi",
  "Món canh",
  "Món rau",
  "Món ăn kèm",
];

const Menu = () => {
  const [dishName, setDishName] = useState(mon_com[0].name);
  const [openFilterModal, setOpenFilterModal] = useState(false);
  const [selectedFilterOption, setSelectedFilterOption] = useState(0);
  const [numberOfDish, setNumberOfDish] = useState(mon_com.length);

  const pageWillBeExitingFrom = useSelector(
    (state) => state.uiReducer.pageExitingFrom
  );

  const dispatch = useDispatch();

  // select option function
  const selectOption = (value) => {
    setSelectedFilterOption(value);
    // Set the number of dishes of each dish category
    if (value === 0) {
      setNumberOfDish(mon_com.length);
    } else if (value === 1) {
      setNumberOfDish(mon_soi.length);
    }
  };

  useEffect(() => {
    dispatch(uiActions.setPageExitingFrom({ exitingPage: "menu" }));
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />

      {pageWillBeExitingFrom == "menu" && (
        <motion.main
          key={"menu_page"}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.8 }}
        >
          <div className="w-full h-[80vh] overflow-y-scroll">
            <div className="w-1/2 h-fit flex flex-col gap-y-5">
              <img
                className="w-[90%] mx-auto"
                src="https://swiperjs.com/demos/images/nature-1.jpg"
              />
              <h1 className="flex-1">Mỳ ý phô mai chay</h1>
            </div>
            <div className="w-1/2 h-fit flex flex-col gap-y-5 mt-40">
              <img
                className="w-[90%] mx-auto"
                src="https://swiperjs.com/demos/images/nature-1.jpg"
              />
              <h1 className="flex-1">Mỳ ý phô mai chay</h1>
            </div>
            <div className="w-1/2 h-fit flex flex-col gap-y-5 mt-40">
              <img
                className="w-[90%] mx-auto"
                src="https://swiperjs.com/demos/images/nature-1.jpg"
              />
              <h1 className="flex-1">Mỳ ý phô mai chay</h1>
            </div>
          </div>

          {/* Bottom contents consitsting of filter button and dish category heading */}
          <BottomContents
            setOpenFilterModal={setOpenFilterModal}
            filter_options={filter_options}
            selectedFilterOption={selectedFilterOption}
            numberOfDish={numberOfDish}
          />

          {/* Filter Modal */}
          <>
            {/* Modal div */}
            <ModalBackground
              openFilterModal={openFilterModal}
              setOpenFilterModal={setOpenFilterModal}
            />
            {/* Bottom Content div */}
            <motion.div
              className="w-full h-[200px] bg-white rounded-t-lg absolute z-[60] bottom-0 p-6"
              key={"modal"}
              initial={{ y: "100%" }}
              animate={openFilterModal ? { y: 0 } : { y: "100%" }}
              transition={{ duration: 0.65, ease: [0.85, 0.01, 0.4, 1] }}
            >
              {filter_options.map((name, index) => (
                <FilterOption
                  key={name}
                  name={name}
                  selectFilterOption={selectOption}
                  index={index}
                  isSelected={selectedFilterOption == index}
                />
              ))}
              <h1
                onClick={() => {
                  setOpenFilterModal(false);
                }}
                className="cursor-pointer absolute bottom-5 right-7 font-medium mt-[55px]"
              >
                Đóng
              </h1>
            </motion.div>
          </>
        </motion.main>
      )}
    </>
  );
};

export default Menu;
