import Head from "next/head";
import Header from "../components/GeneralUI/Header";
import MainContent from "../components/LandingPage/MainContent";
import { motion } from "framer-motion";
import { useDispatch, useSelector } from "react-redux";
import { useEffect } from "react";
import { useRouter } from "next/router";
import { uiActions } from "../store/ui-slice";

export default function Home() {
  const pageWillBeExitingFrom = useSelector(
    (state) => state.uiReducer.pageExitingFrom
  );

  const dispatch = useDispatch();
  const router = useRouter();

  useEffect(() => {
    dispatch(uiActions.setPageExitingFrom({ exitingPage: "home" }));
    router.beforePopState(({ url, as, options }) => {
      // I only want to allow these two routes!

      if (as !== "/" || as === "/") {
        dispatch(uiActions.setPageExitingFrom({ exitingPage: "" }));
        setTimeout(() => {
          router.replace(as);
        }, 1100);
      }
    });
  }, [dispatch]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />

      <motion.main
        key={"home_page"}
        initial={{ opacity: 0 }}
        animate={
          pageWillBeExitingFrom === "home" ? { opacity: 1 } : { opacity: 0 }
        }
        transition={{ duration: 0.6 }}
      >
        <MainContent />
      </motion.main>
    </>
  );
}
