import Head from "next/head";
import Header from "../components/GeneralUI/Header";
import MainContent from "../components/LandingPage/MainContent";
import { motion } from "framer-motion";
import { useSelector } from "react-redux";

export default function Home() {
  const pageWillBeExitingFrom = useSelector(
    (state) => state.uiReducer.pageExitingFrom
  );
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />

      {pageWillBeExitingFrom == "home" && (
        <motion.main
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.8 }}
        >
          <MainContent />
        </motion.main>
      )}
    </>
  );
}
